package info.sarihh.unimodeling.gui;

import java.awt.AlphaComposite;
import java.awt.Graphics;
import java.awt.Graphics2D;
import java.awt.Image;

/*
 * Author: Sari Haj Hussein
 */
public class OriginalLayer extends javax.swing.JPanel {

    private Image planImage;
    private DrawPanel drawPanel;
    private boolean dimmed = false;
    private boolean off = false;

    /**
     * Creates new form OriginalLayer
     */
    public OriginalLayer(DrawPanel drawPanel, Image planImage) {
        this.planImage = planImage;
        this.drawPanel = drawPanel;
        initComponents();
        setSize(planImage.getWidth(null), planImage.getHeight(null));
    }

    @Override
    public void paintComponent(Graphics g) {
        if (dimmed) {
            ((Graphics2D) g).setComposite(
                    AlphaComposite.getInstance(AlphaComposite.SRC_OVER, 0.4f));
        }
        if (!off) {
            g.drawImage(planImage, 0, 0, null);
        }
    }

    public void setImage(Image newImage) {
        this.planImage = newImage;
        setSize(planImage.getWidth(null), planImage.getHeight(null));
        repaint();
    }

    public boolean isDimmed() {
        return dimmed;
    }

    public void setDimmed(boolean dimmed) {
        this.dimmed = dimmed;
        repaint();
    }

    public boolean isOff() {
        return off;
    }

    public void setOff(boolean off) {
        this.off = off;
        repaint();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents
    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
