package info.sarihh.unimodeling.gui;

/*
 * Author: Sari Haj Hussein
 */
public class UserGuideBox extends javax.swing.JDialog {

    public UserGuideBox(java.awt.Frame parent) {
        super(parent);
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        mainPanel = new javax.swing.JPanel();
        guidePanel = new javax.swing.JPanel();
        infoPanel = new javax.swing.JPanel();
        infoScrollPane = new javax.swing.JScrollPane();
        infoTextArea = new javax.swing.JTextArea();
        southPanel = new javax.swing.JPanel();
        okButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("User's Guide: UniModeling 1.0"); // NOI18N
        setModal(true);
        setName("aboutBox"); // NOI18N
        setResizable(false);

        mainPanel.setName("mainPanel"); // NOI18N
        mainPanel.setLayout(new java.awt.BorderLayout());

        guidePanel.setName("guidePanel"); // NOI18N
        guidePanel.setLayout(new java.awt.BorderLayout());

        infoPanel.setName("infoPanel"); // NOI18N
        infoPanel.setLayout(new java.awt.BorderLayout());

        infoScrollPane.setName("infoScrollPane"); // NOI18N

        infoTextArea.setColumns(20);
        infoTextArea.setEditable(false);
        infoTextArea.setFont(new java.awt.Font("Arial 11", 0, 12)); // NOI18N
        infoTextArea.setLineWrap(true);
        infoTextArea.setRows(5);
        infoTextArea.setText("The screenshots at https://sourceforge.net/p/unimodeling/wiki and the following articles:\n-> http://goo.gl/xJ9HB\n-> http://goo.gl/aP8Vj\n-> http://goo.gl/vlvFi\nare sufficient to put UniModeling to work."); // NOI18N
        infoTextArea.setWrapStyleWord(true);
        infoTextArea.setName("infoTextArea"); // NOI18N
        infoTextArea.setCaretPosition(0);
        infoScrollPane.setViewportView(infoTextArea);

        infoPanel.add(infoScrollPane, java.awt.BorderLayout.CENTER);

        guidePanel.add(infoPanel, java.awt.BorderLayout.CENTER);

        mainPanel.add(guidePanel, java.awt.BorderLayout.CENTER);

        southPanel.setName("southPanel"); // NOI18N

        okButton.setText("OK"); // NOI18N
        okButton.setName("okButton"); // NOI18N
        okButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                okButtonActionPerformed(evt);
            }
        });
        southPanel.add(okButton);

        mainPanel.add(southPanel, java.awt.BorderLayout.SOUTH);

        getContentPane().add(mainPanel, java.awt.BorderLayout.CENTER);

        java.awt.Dimension screenSize = java.awt.Toolkit.getDefaultToolkit().getScreenSize();
        setBounds((screenSize.width-353)/2, (screenSize.height-192)/2, 353, 192);
    }// </editor-fold>//GEN-END:initComponents

private void okButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_okButtonActionPerformed
    setVisible(false);
}//GEN-LAST:event_okButtonActionPerformed
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel guidePanel;
    private javax.swing.JPanel infoPanel;
    private javax.swing.JScrollPane infoScrollPane;
    private javax.swing.JTextArea infoTextArea;
    private javax.swing.JPanel mainPanel;
    private javax.swing.JButton okButton;
    private javax.swing.JPanel southPanel;
    // End of variables declaration//GEN-END:variables
}
